version: '3.4'

services:
  webtodo:
    image: webtodo
    build:
      context: .
      dockerfile: WebTodo/Dockerfile
    ports:
      - 5000:80

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password-123
    ports:
      - 1433:1433
