apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
spec:
  hosts:
    - backend
  http:
    - route:
        - destination:
            host: backend
      retries:
        attempts: 3
        perTryTimeout: 200ms
        retryOn: 5xx
      timeout: 2s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sqlserver
spec:
  hosts:
    - sqlserver
  http:
    - route:
        - destination:
            host: sqlserver
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx
spec:
  hosts:
    - nginx
  http:
    - route:
        - destination:
            host: nginx
      retries:
        attempts: 3
        perTryTimeout: 250ms
        retryOn: 5xx
      timeout: 2.5s
