apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: config
              readOnly: true
            - mountPath: /usr/share/nginx/html
              name: pages
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: nginx
            items:
              - key: default.conf
                path: default.conf
        - name: pages
          configMap:
            name: nginx
            items:
              - key: 50x.html
                path: 50x.html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default.conf: |
    upstream backend {
      server backend:80;
    }

    server {
      listen 80 default_server;

      charset utf-8;
      access_log /var/log/nginx/host.access.log main;

      location / {
        proxy_pass http://backend;
        proxy_http_version 1.1;
      }

      error_page 404 /404.html;
      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
        root /usr/share/nginx/html;
      }
    }
  50x.html: |
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Web Todo - service is unavailable</title>
    </head>

    <body>
        <header>
            <h1>Service is unavailable</h1>
        </header>

        <main>
            <p>All backend instances are down and can't serve your response. Wait several minutes and retry your request.
            </p>
        </main>

        <footer>
            Contact us
            <a href="mailto:support@webtodo.com?subject=Service is unavailable issue">support@webtodo.com</a>.
        </footer>
    </body>

    </html>
